import type { Metadata } from "next";
import Link from "next/link";
import { api } from "@/lib/api-client";
import type { ApiProduct } from "@/lib/api-types";
import type { Product } from "@/lib/mock-data";
import { ProductCard } from "@/components/product-card";
import { SponsoredPlacementCard } from "@/components/sponsored-placement-card";
import { BreadcrumbJsonLd, ItemListJsonLd } from "@/components/seo-jsonld";

const SITE_URL = "https://ttflstore.name.ng";
type Category = { id: string; name: string; slug: string; children?: Category[] };
type SponsoredCampaign = { id: string; target_type: "STORE" | "PRODUCT" | "SERVICE" | "COMING_SOON"; storeName: string; storeSlug: string; storeLogoUrl: string | null; storeVerified: boolean; productSlug: string | null; productName: string | null; serviceSlug: string | null; serviceTitle: string | null };
function mapProduct(p: ApiProduct): Product { return { id: p.id, slug: p.slug, name: p.name, price: Number(p.price), previousPrice: p.previousPrice ? Number(p.previousPrice) : undefined, image: p.images?.[0]?.url ?? "", vendor: p.vendor.storeName, vendorSlug: p.vendor.storeSlug, verified: p.vendor.verified, location: p.location ?? p.vendor.location ?? "", rating: p.avgRating ? Number(p.avgRating) : 0, reviewCount: p.reviewCount, sellingMethod: p.sellingMethod === "EXTERNAL_LINK" ? "external" : p.sellingMethod === "WHATSAPP" ? "whatsapp" : "checkout" }; }
async function getCategory(slug: string) { const response = await api.get<{ categories: Category[] }>("/api/categories"); return response.categories.flatMap(c => [c, ...(c.children ?? [])]).find(c => c.slug === slug); }
async function getProducts(slug: string): Promise<ApiProduct[]> { const response = await api.get<{ items: ApiProduct[] }>(`/api/products?category=${encodeURIComponent(slug)}&limit=24&page=1&sort=newest`); return response.items ?? []; }
async function getSponsored(slug: string): Promise<SponsoredCampaign[]> { try { const response = await api.get<{ campaigns: SponsoredCampaign[] }>(`/api/ads/active?category=${encodeURIComponent(slug)}`); return response.campaigns ?? []; } catch { return []; } }
export async function generateMetadata({ params }: { params: { slug: string } }): Promise<Metadata> { const category = await getCategory(params.slug).catch(() => undefined); const name = category?.name ?? params.slug.replace(/-/g, " "); return { title: `${name} — Buy & Sell in Nigeria`, description: `Browse ${name} products from vendors across Nigeria on TTFL Store.`, alternates: { canonical: `${SITE_URL}/categories/${params.slug}` }, openGraph: { title: `${name} | TTFL Store`, description: `Browse ${name} products on TTFL Store.`, url: `${SITE_URL}/categories/${params.slug}`, images: ["/ttflstore.png"] } }; }
export default async function CategoryPage({ params }: { params: { slug: string } }) { const [category, products, sponsored] = await Promise.all([getCategory(params.slug).catch(() => undefined), getProducts(params.slug).catch(() => []), getSponsored(params.slug)]); const name = category?.name ?? params.slug.replace(/-/g, " "); const mapped = products.map(mapProduct); return <main className="shell py-8 sm:py-12"><BreadcrumbJsonLd items={[{ name: "Home", url: "/" }, { name: "Categories", url: "/categories" }, { name, url: `/categories/${params.slug}` }]} /><ItemListJsonLd name={`${name} products`} items={products.map(p => ({ name: p.name, url: `/products/${p.slug}`, image: p.images?.[0]?.url }))} /><nav className="text-xs text-graphite-500"><Link href="/">Home</Link> <span aria-hidden="true">/</span> <Link href="/categories">Categories</Link> <span aria-hidden="true">/</span> <span>{name}</span></nav><h1 className="mt-3 text-3xl font-bold capitalize text-graphite-950">{name}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-graphite-600">Shop {name} from sellers across Nigeria on TTFL Store.</p>{sponsored.length > 0 && <section aria-label={`Sponsored ${name} results`} className="mt-7"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-bold text-graphite-900">Sponsored in {name}</h2><span className="text-[11px] font-semibold uppercase tracking-wide text-ember-600">Paid placement</span></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{sponsored.slice(0, 6).map(c => <SponsoredPlacementCard key={c.id} campaign={c} />)}</div></section>}{mapped.length ? <div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{mapped.map(p => <ProductCard key={p.id} product={p} />)}</div> : <div className="mt-8 rounded-card border border-dashed border-graphite-300 p-10 text-center text-sm text-graphite-600">No products are available in this category yet.</div>}</main>; }
