"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { api, ApiError } from "@/lib/api-client";
import { TextField } from "@/components/text-field";
import { ImageUploadField, type UploadedImage } from "@/components/image-upload-field";
import type { ApiCategory, SellingMethod, ProductCondition } from "@/lib/api-types";

export type ProductFormValues = {
  name: string; brand: string; specifications: Record<string,string>; description: string; categorySlug: string; price: string; previousPrice: string;
  condition: ProductCondition; stock: string; location: string; images: UploadedImage[];
  tags: string[]; sellingMethod: SellingMethod; externalUrl: string; whatsappNumber: string; estimatedDeliveryDays: string;
  comingSoon: boolean; availableAt: string;
};
const EMPTY: ProductFormValues = {
  name: "", brand: "", specifications: {}, description: "", categorySlug: "", price: "", previousPrice: "", condition: "NEW", stock: "1",
  location: "", images: [], tags: [], sellingMethod: "CHECKOUT", externalUrl: "", whatsappNumber: "", estimatedDeliveryDays: "7",
  comingSoon: false, availableAt: "",
};
export function ProductForm({ productId, initial, redirectTo }: { productId?: string; initial?: Partial<ProductFormValues>; redirectTo?: string }) {
  const router = useRouter(); const [categories, setCategories] = useState<ApiCategory[]>([]); const [loadingCategories, setLoadingCategories] = useState(true);
  const [form, setForm] = useState<ProductFormValues>({ ...EMPTY, ...initial }); const [tagInput, setTagInput] = useState(""); const [error, setError] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { let mounted = true; async function loadCategories() { try { setLoadingCategories(true); const response = await api.get<{ categories: ApiCategory[] }>("/api/categories"); if (mounted) setCategories(response.categories); } catch (err) { if (mounted) setError(err instanceof ApiError ? err.message : "Unable to load product categories. Please refresh the page and try again."); } finally { if (mounted) setLoadingCategories(false); } } void loadCategories(); return () => { mounted = false; }; }, []);
  function set<K extends keyof ProductFormValues>(key: K, value: ProductFormValues[K]) { setForm((current) => ({ ...current, [key]: value })); }
  function addTagsFromInput(value: string) { const incoming = value.split(",").map((tag) => tag.trim().toLowerCase()).filter(Boolean); if (!incoming.length) return; setForm((current) => ({ ...current, tags: Array.from(new Set([...current.tags, ...incoming])).slice(0, 20) })); setTagInput(""); }
  function removeTag(tag: string) { setForm((current) => ({ ...current, tags: current.tags.filter((item) => item !== tag) })); }
  async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault(); setError(null); if (!form.name.trim() || form.name.trim().length < 3) return setError("Product name must be at least 3 characters."); if (form.brand.trim().length > 80) return setError("Brand name is too long."); if (!form.description.trim() || form.description.trim().length < 10) return setError("Product description must be at least 10 characters."); if (!form.categorySlug) return setError("Please choose a product category."); if (!form.comingSoon && (!form.price || Number(form.price) <= 0)) return setError("Please enter a valid product price."); if (form.previousPrice && Number(form.previousPrice) <= Number(form.price)) return setError("Previous price must be greater than the current price."); if (Number(form.stock) < 0) return setError("Stock cannot be negative."); if (form.images.length === 0) return setError("Please add at least one product photo."); const deliveryDays = Number(form.estimatedDeliveryDays); if (!Number.isInteger(deliveryDays) || deliveryDays < 1 || deliveryDays > 90) return setError("Estimated delivery must be between 1 and 90 days."); if (form.sellingMethod === "EXTERNAL_LINK" && !form.externalUrl.trim()) return setError("Please enter the product URL for the external link."); if (form.sellingMethod === "EXTERNAL_LINK") { try { new URL(form.externalUrl.trim()); } catch { return setError("Please enter a valid external purchase URL."); } } if (form.sellingMethod === "WHATSAPP" && form.whatsappNumber.trim() && form.whatsappNumber.trim().length < 7) return setError("Please enter a valid WhatsApp number."); addTagsFromInput(tagInput);
    setSubmitting(true); const images = form.images.map((image) => image.url).filter(Boolean); const tags = Array.from(new Set([...form.tags, ...tagInput.split(",").map((tag) => tag.trim().toLowerCase()).filter(Boolean)])).slice(0, 20);
    const specifications = { ...form.specifications };
    if (form.brand.trim()) specifications.brand = form.brand.trim(); else delete specifications.brand;
    const rawName = form.name.trim(); const brand = form.brand.trim(); const searchableName = brand && !rawName.toLowerCase().startsWith(`${brand.toLowerCase()} `) ? `${brand} ${rawName}` : rawName;
    const payload: Record<string, unknown> = { name: searchableName, description: form.description.trim(), categorySlug: form.categorySlug, price: form.price.trim() ? Number(form.price) : 0, condition: form.condition, stock: Number(form.stock), images, tags, specifications, sellingMethod: form.sellingMethod, estimatedDeliveryDays: deliveryDays, comingSoon: form.comingSoon, availableAt: form.availableAt ? new Date(form.availableAt).toISOString() : null };
    if (form.previousPrice.trim()) payload.previousPrice = Number(form.previousPrice); if (form.location.trim()) payload.location = form.location.trim(); if (form.sellingMethod === "EXTERNAL_LINK") payload.externalUrl = form.externalUrl.trim(); if (form.sellingMethod === "WHATSAPP" && form.whatsappNumber.trim()) payload.whatsappNumber = form.whatsappNumber.trim();
    try { if (productId) await api.patch(`/api/products/${productId}`, payload); else await api.post("/api/products", payload); router.push(redirectTo || "/vendor/dashboard/products"); } catch (err) { setError(err instanceof ApiError ? err.message : "Something went wrong while saving the product."); setSubmitting(false); }
  }
  return <form onSubmit={handleSubmit} className="flex flex-col gap-4">
    <TextField label="Product name" value={form.name} onChange={(value) => set("name", value)} hint="Enter the model/product name. The selected brand will also be included for search discovery." />
    <TextField label="Brand" value={form.brand} onChange={(value) => set("brand", value)} optional hint="Add the manufacturer or brand, e.g. Samsung, Apple, HP or Nike. This is used for search and Product structured data." />
    <label className="flex flex-col gap-1 text-sm"><span className="font-medium text-graphite-700 dark:text-graphite-300">Description</span><textarea required rows={5} value={form.description} onChange={(e) => set("description", e.target.value)} className="rounded-[7px] border border-graphite-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-ember-600 dark:border-graphite-700 dark:bg-graphite-900 dark:text-white" /></label>
    <label className="flex flex-col gap-1 text-sm"><span className="font-medium text-graphite-700 dark:text-graphite-300">Category</span><select required value={form.categorySlug} onChange={(e) => set("categorySlug", e.target.value)} disabled={loadingCategories || categories.length === 0} className="rounded-[7px] border border-graphite-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-ember-600 disabled:cursor-not-allowed disabled:bg-cloud-100 dark:border-graphite-700 dark:bg-graphite-900 dark:text-white"><option value="" disabled>{loadingCategories ? "Loading categories..." : categories.length === 0 ? "No categories available" : "Choose a category"}</option>{categories.map((category) => <option key={category.id} value={category.slug}>{category.name}</option>)}</select></label>
    <div className="grid grid-cols-2 gap-3"><TextField label={form.comingSoon ? "Price (optional)" : "Price (₦)"} type="number" value={form.price} onChange={(value) => set("price", value)} optional={form.comingSoon} hint={form.comingSoon ? "You can add the price later before launch." : undefined} /><TextField label="Previous price" type="number" value={form.previousPrice} onChange={(value) => set("previousPrice", value)} optional hint="Only enter this if discounted." /></div>
    <div className="grid grid-cols-2 gap-3"><label className="flex flex-col gap-1 text-sm"><span className="font-medium text-graphite-700 dark:text-graphite-300">Condition</span><select value={form.condition} onChange={(e) => set("condition", e.target.value as ProductCondition)} className="rounded-[7px] border border-graphite-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-ember-600 dark:border-graphite-700 dark:bg-graphite-900 dark:text-white"><option value="NEW">New</option><option value="USED">Used</option></select></label><TextField label="Stock" type="number" value={form.stock} onChange={(value) => set("stock", value)} /></div>
    <TextField label="Location" value={form.location} onChange={(value) => set("location", value)} optional hint="Optional — e.g. Lagos, Abuja, Port Harcourt." />
    <div className="rounded-card border border-graphite-200 p-4 dark:border-graphite-700"><div className="text-sm font-medium text-graphite-700 dark:text-graphite-300">Search tags</div><p className="mt-1 text-xs text-graphite-500 dark:text-graphite-400">Add words customers might search for. Example: laptop, laptops, HP, MacBook, computer, notebook.</p><div className="mt-3 flex gap-2"><input value={tagInput} onChange={(e) => setTagInput(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" || e.key === ",") { e.preventDefault(); addTagsFromInput(tagInput); } }} placeholder="Type a tag and press Enter" className="min-w-0 flex-1 rounded-[7px] border border-graphite-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-ember-600 dark:border-graphite-700 dark:bg-graphite-900 dark:text-white" /><button type="button" onClick={() => addTagsFromInput(tagInput)} className="rounded-[7px] border border-graphite-200 px-4 py-2 text-sm font-semibold hover:bg-cloud-100 dark:border-graphite-700 dark:hover:bg-graphite-800">Add</button></div>{form.tags.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{form.tags.map((tag) => <button key={tag} type="button" onClick={() => removeTag(tag)} className="rounded-full bg-cloud-100 px-3 py-1 text-xs font-medium text-graphite-700 hover:bg-ember-100 hover:text-ember-700 dark:bg-graphite-800 dark:text-graphite-200">{tag} ×</button>)}</div>}</div>
    <div className="rounded-card border border-graphite-200 p-4 dark:border-graphite-700"><TextField label="Estimated delivery (days)" type="number" value={form.estimatedDeliveryDays} onChange={(value) => set("estimatedDeliveryDays", value)} hint="Customers will see an estimated delivery date." /></div>
    <div className="rounded-card border border-ember-200 bg-ember-50/60 p-4 dark:border-ember-900/60 dark:bg-ember-950/20"><label className="flex items-start gap-3"><input type="checkbox" checked={form.comingSoon} onChange={(e) => set("comingSoon", e.target.checked)} className="mt-1 h-4 w-4" /><span><span className="block text-sm font-semibold text-graphite-900 dark:text-white">Coming soon</span><span className="mt-1 block text-xs leading-5 text-graphite-600 dark:text-graphite-400">Use this for products announced before launch. Customers can view the product and tap Notify me instead of buying it.</span></span></label>{form.comingSoon && <div className="mt-4"><TextField label="Expected availability" type="datetime-local" value={form.availableAt} onChange={(value) => set("availableAt", value)} optional hint="Optional. You can make the product available manually or through a launch campaign." /></div>}</div>
    <ImageUploadField images={form.images} onChange={(images) => set("images", images)} />
    {form.images.length === 0 && <p className="text-xs text-ember-600">Add at least one product photo.</p>}
    <fieldset className="rounded-card border border-graphite-200 p-4 dark:border-graphite-700"><legend className="px-1 text-sm font-semibold text-graphite-900 dark:text-white">How do customers buy this?</legend><div className="mt-2 flex flex-col gap-2">{([{ value: "CHECKOUT", label: "TTFL Store checkout — customer pays through the site" }, { value: "EXTERNAL_LINK", label: "External link — send them to my own website" }, { value: "WHATSAPP", label: "WhatsApp — chat to close the sale" }] as const).map((option) => <label key={option.value} className="flex items-center gap-2 text-sm text-graphite-700 dark:text-graphite-300"><input type="radio" name="sellingMethod" checked={form.sellingMethod === option.value} onChange={() => set("sellingMethod", option.value)} />{option.label}</label>)}</div>{form.sellingMethod === "EXTERNAL_LINK" && <div className="mt-3"><TextField label="Product URL on your website" value={form.externalUrl} onChange={(value) => set("externalUrl", value)} hint="Required only when External link is selected." /></div>}{form.sellingMethod === "WHATSAPP" && <div className="mt-3"><TextField label="WhatsApp number for this product" value={form.whatsappNumber} onChange={(value) => set("whatsappNumber", value)} optional hint="Optional — if blank, your store's WhatsApp number will be used." /></div>}</fieldset>
    {error && <p role="alert" className="rounded-[7px] bg-ember-100 px-3 py-2 text-sm text-ember-700">{error}</p>}
    <button type="submit" disabled={submitting || loadingCategories || categories.length === 0} className="rounded-card bg-ember-600 py-3 text-sm font-semibold text-white hover:bg-ember-700 disabled:cursor-not-allowed disabled:opacity-60">{submitting ? "Saving…" : productId ? "Save changes" : form.comingSoon ? "Create Coming Soon product" : "List product"}</button>
  </form>;
}
