"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { BarChart3, Check, Copy, ExternalLink, Link2, Loader2, Wallet, Gift, UserRound } from "lucide-react";
import { api, ApiError } from "@/lib/api-client";
import { useAuth } from "@/lib/auth-context";
import { formatNaira } from "@/lib/mock-data";

const STORE_URL="https://ttflstore.name.ng";
type Dashboard={affiliate:{id:string;code:string;vendorCode:string;status:string;commissionRate:number;clicks:number;conversions:number;pendingEarnings:number;paidEarnings:number;displayName:string;displayAvatarUrl:string|null};commissions:Array<{id:string;orderNumber:string;orderAmount:number;amount:number;status:string;createdAt:string}>;vendorRewards:Array<any>};

export default function AffiliateDashboardPage(){
 const{user,loading:authLoading}=useAuth();const[dashboard,setDashboard]=useState<Dashboard|null>(null);const[loading,setLoading]=useState(true);const[joining,setJoining]=useState(false);const[saving,setSaving]=useState(false);const[copied,setCopied]=useState<string|null>(null);const[displayName,setDisplayName]=useState("");const[error,setError]=useState<string|null>(null);
 async function load(){setLoading(true);try{const res=await api.get<{dashboard:Dashboard|null}>("/api/affiliates/dashboard");setDashboard(res.dashboard);if(res.dashboard)setDisplayName(res.dashboard.affiliate.displayName||"");}catch(err){setError(err instanceof ApiError?err.message:"Unable to load your affiliate dashboard.");}finally{setLoading(false);}}
 useEffect(()=>{if(user)void load();else if(!authLoading)setLoading(false);},[user,authLoading]);
 async function join(){setJoining(true);setError(null);try{await api.post("/api/affiliates/join");await load();}catch(err){setError(err instanceof ApiError?err.message:"Unable to create your affiliate account.");}finally{setJoining(false);}}
 async function saveProfile(){setSaving(true);setError(null);try{const res=await api.patch<{dashboard:Dashboard}>("/api/affiliates/profile",{displayName});setDashboard(res.dashboard);}catch(err){setError(err instanceof ApiError?err.message:"Unable to save your affiliate profile.");}finally{setSaving(false);}}
 async function copy(label:string,value:string){await navigator.clipboard.writeText(value);setCopied(label);window.setTimeout(()=>setCopied(null),1800);}
 if(authLoading||loading)return <div className="shell flex min-h-[60vh] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-ember-600"/></div>;
 if(!user)return <div className="shell py-16 text-center"><h1 className="text-xl font-bold text-graphite-900">Log in to access your affiliate dashboard</h1><Link href="/login?next=/affiliate/dashboard" className="mt-6 inline-block rounded-card bg-ember-600 px-5 py-2.5 text-sm font-semibold text-white">Log in</Link></div>;
 if(!dashboard)return <div className="shell py-16"><div className="mx-auto max-w-2xl rounded-card border border-graphite-200 bg-white p-8 text-center"><Wallet className="mx-auto h-10 w-10 text-ember-600"/><h1 className="mt-4 text-2xl font-bold text-graphite-900">Become a TTFL Store affiliate</h1><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-graphite-600">Create your affiliate account to get separate customer and vendor referral links.</p><button onClick={join} disabled={joining} className="mt-6 rounded-card bg-ember-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{joining?"Creating account…":"Create affiliate account"}</button>{error&&<p className="mt-3 text-sm text-ember-700">{error}</p>}</div></div>;
 const a=dashboard.affiliate;const customerLink=`${STORE_URL}/?ref=${encodeURIComponent(a.code)}&type=customer`;const vendorLink=`${STORE_URL}/?ref=${encodeURIComponent(a.vendorCode)}&type=vendor`;const conversionRate=a.clicks?((a.conversions/a.clicks)*100).toFixed(1):"0.0";
 return <div className="shell py-8 sm:py-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-wide text-ember-600">Affiliate dashboard</p><h1 className="mt-1 text-2xl font-bold text-graphite-900">Grow your referrals</h1><p className="mt-1 text-sm text-graphite-600">Share the right link for customers or new vendors.</p></div><Link href="/affiliate" className="text-sm font-semibold text-graphite-700 hover:text-ember-600">Program details →</Link></div>
 <section className="mt-6 grid gap-4 lg:grid-cols-2"><ReferralLink title="Customer referral link" description="Tracks qualifying customer orders. No vendor invitation popup." link={customerLink} copied={copied==="customer"} onCopy={()=>copy("customer",customerLink)} onOpen={()=>window.open(customerLink,"_blank","noopener,noreferrer")}/><ReferralLink title="Vendor referral link" description="Shows your public affiliate name and the current vendor reward." link={vendorLink} copied={copied==="vendor"} onCopy={()=>copy("vendor",vendorLink)} onOpen={()=>window.open(vendorLink,"_blank","noopener,noreferrer")}/></section>
 <section className="mt-5 rounded-card border border-graphite-200 bg-white p-5"><div className="flex items-center gap-2"><UserRound className="h-5 w-5 text-ember-600"/><h2 className="text-sm font-bold">Public referral identity</h2></div><p className="mt-1 text-xs text-graphite-500">This name is shown to people who enter through your vendor referral link.</p><div className="mt-4 flex flex-col gap-3 sm:flex-row"><input value={displayName} onChange={e=>setDisplayName(e.target.value)} maxLength={80} className="min-w-0 flex-1 rounded-xl border border-graphite-200 px-3 py-2.5 text-sm outline-none focus:border-ember-600"/><button onClick={saveProfile} disabled={saving||displayName.trim().length<2} className="rounded-xl bg-graphite-900 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{saving?"Saving…":"Save display name"}</button></div></section>
 <section className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Stat icon={<Wallet/>} label="Pending earnings" value={formatNaira(a.pendingEarnings)}/><Stat icon={<Wallet/>} label="Paid earnings" value={formatNaira(a.paidEarnings)}/><Stat icon={<BarChart3/>} label="Clicks" value={a.clicks.toLocaleString()}/><Stat icon={<BarChart3/>} label="Conversions" value={`${a.conversions.toLocaleString()} (${conversionRate}%)`}/></section>
 <section className="mt-6 rounded-card border border-graphite-200 bg-white"><div className="border-b border-graphite-200 p-5"><h2 className="text-sm font-bold">Vendor referral rewards</h2><p className="mt-1 text-xs text-graphite-500">See which invited users claimed or redeemed your configured vendor perk.</p></div>{dashboard.vendorRewards.length===0?<div className="p-8 text-center text-sm text-graphite-500">No vendor referral rewards yet.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-cloud-100 text-xs text-graphite-500"><tr><th className="px-5 py-3">User</th><th className="px-5 py-3">Reward</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Claimed</th></tr></thead><tbody className="divide-y divide-graphite-100">{dashboard.vendorRewards.map(r=><tr key={r.id}><td className="px-5 py-3 font-semibold">{[r.firstName,r.lastName].filter(Boolean).join(" ")||r.email}</td><td className="px-5 py-3">{r.rewardMonths} month {r.rewardTier}</td><td className="px-5 py-3">{r.status}</td><td className="px-5 py-3 text-xs text-graphite-500">{new Date(r.claimedAt).toLocaleDateString()}</td></tr>)}</tbody></table></div>}</section>
 <section className="mt-8 rounded-card border border-graphite-200 bg-white"><div className="border-b border-graphite-200 p-5"><h2 className="text-sm font-bold">Commission history</h2></div>{dashboard.commissions.length===0?<div className="p-8 text-center text-sm text-graphite-500">No commissions yet.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-cloud-100 text-xs text-graphite-500"><tr><th className="px-5 py-3">Order</th><th className="px-5 py-3">Order value</th><th className="px-5 py-3">Commission</th><th className="px-5 py-3">Status</th></tr></thead><tbody className="divide-y divide-graphite-100">{dashboard.commissions.map(c=><tr key={c.id}><td className="px-5 py-3 font-mono text-xs">{c.orderNumber}</td><td className="px-5 py-3">{formatNaira(c.orderAmount)}</td><td className="px-5 py-3 font-semibold">{formatNaira(c.amount)}</td><td className="px-5 py-3">{c.status}</td></tr>)}</tbody></table></div>}</section>
 {error&&<p className="mt-4 rounded-xl bg-ember-50 px-4 py-3 text-sm text-ember-700">{error}</p>}</div>;
}
function ReferralLink({title,description,link,copied,onCopy,onOpen}:{title:string;description:string;link:string;copied:boolean;onCopy:()=>void;onOpen:()=>void}){return <div className="rounded-card border border-graphite-200 bg-white p-5"><p className="text-xs font-bold uppercase tracking-wide text-ember-600">{title}</p><p className="mt-1 text-xs leading-5 text-graphite-500">{description}</p><div className="mt-3 flex items-center gap-2 rounded-xl border border-graphite-200 bg-cloud-100 px-3 py-2.5"><Link2 className="h-4 w-4 shrink-0 text-ember-600"/><span className="truncate font-mono text-xs">{link}</span></div><div className="mt-3 flex gap-2"><button onClick={onCopy} className="inline-flex items-center gap-2 rounded-xl bg-graphite-900 px-4 py-2.5 text-sm font-semibold text-white">{copied?<Check className="h-4 w-4"/>:<Copy className="h-4 w-4" />}{copied?"Copied":"Copy"}</button><button onClick={onOpen} className="inline-flex items-center gap-2 rounded-xl border border-graphite-200 px-4 py-2.5 text-sm font-semibold"><ExternalLink className="h-4 w-4"/>Open</button></div></div>}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-card border border-graphite-200 bg-white p-5"><div className="text-ember-600">{icon}</div><p className="mt-3 text-xs font-medium text-graphite-500">{label}</p><p className="mt-1 text-lg font-bold text-graphite-900">{value}</p></div>}
