"use client";

import { useEffect,useState } from "react";
import Link from "next/link";
import { ArrowLeft, Check, Gift, X } from "lucide-react";
import { api,ApiError } from "@/lib/api-client";

export default function AdminEventsPage(){
 const [partners,setPartners]=useState<any[]>([]);const [events,setEvents]=useState<any[]>([]);const [error,setError]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState<string|null>(null);
 async function load(){try{const [p,e]=await Promise.all([api.get<{partners:any[]}>("/api/partner-events/admin/partners"),api.get<{events:any[]}>("/api/partner-events/admin/events")]);setPartners(p.partners);setEvents(e.events)}catch(e){setError(e instanceof ApiError?e.message:"Could not load partner events.")}}
 useEffect(()=>{void load()},[]);
 async function eventStatus(id:string,status:string){setBusy(id);try{await api.patch(`/api/partner-events/admin/events/${id}/status`,{status});setMessage(`Event ${status.toLowerCase()}.`);await load()}catch(e){setError(e instanceof ApiError?e.message:"Could not update event.")}finally{setBusy(null)}}
 async function grant(id:string){setBusy(id);try{await api.patch(`/api/partner-events/admin/partners/${id}/event-access`,{plan:"ENTERPRISE",complimentary:true,reason:"Strategic partnership"});setMessage("Complimentary Enterprise Event Plan granted.");await load()}catch(e){setError(e instanceof ApiError?e.message:"Could not grant access.")}finally{setBusy(null)}}
 return <div className="shell py-8"><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-semibold text-graphite-600 dark:text-graphite-300"><ArrowLeft className="h-4 w-4"/>Admin</Link><div className="mt-5"><h1 className="text-2xl font-extrabold text-graphite-900 dark:text-white">Partner Events</h1><p className="mt-1 text-sm text-graphite-600 dark:text-graphite-300">Approve partner applications, grant complimentary event plans and publish submitted events.</p></div>{message&&<p className="mt-4 rounded-card bg-verified-100 px-3 py-2 text-sm text-verified-700">{message}</p>}{error&&<p className="mt-4 rounded-card bg-ember-100 px-3 py-2 text-sm text-ember-700">{error}</p>}
 <section className="mt-6 rounded-card border border-graphite-200 bg-white p-5 dark:border-graphite-700 dark:bg-graphite-900"><h2 className="font-bold text-graphite-900 dark:text-white">Partner applications</h2><div className="mt-3 divide-y divide-graphite-200 border-t border-graphite-200">{partners.length===0?<p className="py-4 text-sm text-graphite-600">No partners yet.</p>:partners.map(p=><div key={p.id} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold text-graphite-900 dark:text-white">{p.organizationName}</p><p className="text-xs text-graphite-600 dark:text-graphite-300">{p.owner?.email} · {p.status} · {p.eventPlan} plan · {p._count?.events??0} events</p></div><div className="flex flex-wrap gap-2">{p.status==="PENDING"&&<button onClick={()=>{void api.patch(`/api/partner-events/admin/partners/${p.id}/status`,{status:"APPROVED"}).then(()=>load())}} className="rounded-card bg-verified-600 px-3 py-2 text-xs font-bold text-white">Approve</button>}<button onClick={()=>void grant(p.id)} disabled={busy===p.id} className="inline-flex items-center gap-1 rounded-card border border-graphite-200 px-3 py-2 text-xs font-bold text-graphite-800 dark:border-graphite-700 dark:text-white"><Gift className="h-3.5 w-3.5"/>{p.complimentaryAccess?"Access active":"Grant free plan"}</button></div></div>)}</div></section>
 <section className="mt-6 rounded-card border border-graphite-200 bg-white p-5 dark:border-graphite-700 dark:bg-graphite-900"><h2 className="font-bold text-graphite-900 dark:text-white">Submitted events</h2><div className="mt-3 space-y-3">{events.length===0?<p className="text-sm text-graphite-600">No submitted events yet.</p>:events.map(e=><div key={e.id} className="rounded-card border border-graphite-200 p-4 dark:border-graphite-700"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-bold text-graphite-900 dark:text-white">{e.title}</p><p className="mt-1 text-xs text-graphite-600 dark:text-graphite-300">{e.partner.organizationName} · {e.status} · {e.eventPlan} plan</p><p className="mt-1 text-xs text-graphite-600 dark:text-graphite-300">{new Date(e.startsAt).toLocaleString()}</p></div>{e.status==="PENDING_REVIEW"&&<div className="flex gap-2"><button onClick={()=>void eventStatus(e.id,"PUBLISHED")} disabled={busy===e.id} className="inline-flex items-center gap-1 rounded-card bg-verified-600 px-3 py-2 text-xs font-bold text-white"><Check className="h-3.5 w-3.5"/>Publish</button><button onClick={()=>void eventStatus(e.id,"REJECTED")} disabled={busy===e.id} className="inline-flex items-center gap-1 rounded-card border border-ember-200 px-3 py-2 text-xs font-bold text-ember-700"><X className="h-3.5 w-3.5"/>Reject</button></div>}</div></div>)}</div></section>
 </div>
}
