"use client";
import { useEffect, useState } from "react";
import { api, ApiError } from "@/lib/api-client";
import { formatNaira } from "@/lib/mock-data";
type Product = { id:string; name:string; price:string; comingSoon?:boolean; status:string; vendor:{storeName:string} };
type Store = { id:string; storeName:string; storeSlug:string; status:string };
type FeaturedProductRow = { id:string; placement:string; durationDays:number; price:string; status:string; endDate:string|null; product:{name:string;vendor:{storeName:string}} };
type FeaturedStoreRow = { id:string; durationDays:number; price:string; status:string; endDate:string|null; vendor:{storeName:string} };
type FlashDeal = { id:string; productId:string; name:string; discountPercent:number|string; salePrice:number|string; endsAt:string; storeName:string };
const durationOptions=[1,7,14,30] as const;
function toIso(value:string){return value?new Date(value).toISOString():new Date().toISOString();}
export default function AdminFeaturedPage(){
 const[products,setProducts]=useState<FeaturedProductRow[]|null>(null);const[stores,setStores]=useState<FeaturedStoreRow[]|null>(null);const[flashDeals,setFlashDeals]=useState<FlashDeal[]>([]);const[catalog,setCatalog]=useState<Product[]>([]);const[vendorStores,setVendorStores]=useState<Store[]>([]);
 const[flashProduct,setFlashProduct]=useState("");const[flashDiscount,setFlashDiscount]=useState("20");const[flashStart,setFlashStart]=useState("");const[flashEnd,setFlashEnd]=useState("");const[featuredProduct,setFeaturedProduct]=useState("");const[featuredPlacement,setFeaturedPlacement]=useState("HOMEPAGE");const[featuredProductDuration,setFeaturedProductDuration]=useState("7");const[featuredStore,setFeaturedStore]=useState("");const[featuredStoreDuration,setFeaturedStoreDuration]=useState("7");const[saving,setSaving]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);
 async function load(){try{const[pRes,sRes,fRes,cRes,vRes]=await Promise.all([api.get<{items:FeaturedProductRow[]}>("/api/featured/products?placement=HOMEPAGE&limit=50"),api.get<{items:FeaturedStoreRow[]}>("/api/featured/stores?limit=50"),api.get<{deals:FlashDeal[]}>("/api/flash-deals"),api.get<{items:Product[]}>("/api/products/admin/list?limit=100&page=1"),api.get<{items:Store[]}>("/api/vendors/stores?limit=100&page=1")]);setProducts(pRes.items);setStores(sRes.items);setFlashDeals(fRes.deals);setCatalog(cRes.items);setVendorStores(vRes.items.filter(s=>s.status==="APPROVED"));}catch(err){setError(err instanceof ApiError?err.message:"Could not load promotion data.");}}
 useEffect(()=>{void load();},[]);
 async function cancelProduct(id:string){if(!confirm("Cancel this featured product listing?"))return;await api.post(`/api/featured/products/${id}/cancel`);await load();}async function cancelStore(id:string){if(!confirm("Cancel this featured store listing?"))return;await api.post(`/api/featured/stores/${id}/cancel`);await load();}async function cancelFlash(id:string){if(!confirm("Remove this flash deal now?"))return;setSaving(`cancel-${id}`);try{await api.delete(`/api/flash-deals/admin/${id}`);await load();}catch(err){setError(err instanceof ApiError?err.message:"Could not remove flash deal.");}finally{setSaving(null);}}
 async function createFlash(e:React.FormEvent){e.preventDefault();setSaving("flash");setError(null);try{await api.post("/api/flash-deals/admin",{productId:flashProduct,discountPercent:Number(flashDiscount),startsAt:toIso(flashStart),endsAt:toIso(flashEnd)});setFlashProduct("");await load();}catch(err){setError(err instanceof ApiError?err.message:"Could not create flash deal.");}finally{setSaving(null);}}
 async function createFeaturedProduct(e:React.FormEvent){e.preventDefault();setSaving("product");setError(null);try{await api.post("/api/featured/admin/products",{productId:featuredProduct,placement:featuredPlacement,durationDays:Number(featuredProductDuration)});setFeaturedProduct("");await load();}catch(err){setError(err instanceof ApiError?err.message:"Could not feature product.");}finally{setSaving(null);}}
 async function createFeaturedStore(e:React.FormEvent){e.preventDefault();setSaving("store");setError(null);try{await api.post("/api/featured/admin/stores",{vendorId:featuredStore,durationDays:Number(featuredStoreDuration)});setFeaturedStore("");await load();}catch(err){setError(err instanceof ApiError?err.message:"Could not feature store.");}finally{setSaving(null);}}
 const availableProducts=catalog.filter(p=>p.status==="ACTIVE"&&!p.comingSoon);
 return <div className="shell py-8"><h1 className="text-xl font-bold text-graphite-900">Featured & promotions</h1><p className="mt-1 text-sm text-graphite-600">Admins can place products and stores on demand without a vendor payment. Coming-soon products are excluded from promotions.</p>{error&&<p className="mt-4 rounded-card bg-ember-100 px-3 py-2 text-sm text-ember-700">{error}</p>}
 <div className="mt-6 grid gap-4 lg:grid-cols-3">
 <form onSubmit={createFlash} className="rounded-card border border-graphite-200 p-4"><h2 className="font-bold text-graphite-900">⚡ On-demand flash deal</h2><p className="mt-1 text-xs text-graphite-600">Choose an available product, discount and time window.</p><select required value={flashProduct} onChange={e=>setFlashProduct(e.target.value)} className="mt-4 w-full rounded-card border border-graphite-200 px-3 py-2.5 text-sm"><option value="">Choose product</option>{availableProducts.map(p=><option key={p.id} value={p.id}>{p.name} — {formatNaira(Number(p.price))}</option>)}</select><input required type="number" min="1" max="99" value={flashDiscount} onChange={e=>setFlashDiscount(e.target.value)} placeholder="Discount %" className="mt-2 w-full rounded-card border border-graphite-200 px-3 py-2.5 text-sm"/><input required type="datetime-local" value={flashStart} onChange={e=>setFlashStart(e.target.value)} className="mt-2 w-full rounded-card border border-graphite-200 px-3 py-2.5 text-sm"/><input required type="datetime-local" value={flashEnd} onChange={e=>setFlashEnd(e.target.value)} className="mt-2 w-full rounded-card border border-graphite-200 px-3 py-2.5 text-sm"/><button disabled={saving!==null} className="mt-3 w-full rounded-card bg-ember-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{saving==="flash"?"Adding…":"Add flash deal"}</button></form>
 <form onSubmit={createFeaturedProduct} className="rounded-card border border-graphite-200 p-4"><h2 className="font-bold text-graphite-900">⭐ Feature a product</h2><p className="mt-1 text-xs text-graphite-600">Admin-sponsored placement, no vendor payment required.</p><select required value={featuredProduct} onChange={e=>setFeaturedProduct(e.target.value)} className="mt-4 w-full rounded-card border border-graphite-200 px-3 py-2.5 text-sm"><option value="">Choose product</option>{availableProducts.map(p=><option key={p.id} value={p.id}>{p.name} — {p.vendor.storeName}</option>)}</select><select value={featuredPlacement} onChange={e=>setFeaturedPlacement(e.target.value)} className="mt-2 w-full rounded-card border border-graphite-200 px-3 py-2.5 text-sm"><option value="HOMEPAGE">Homepage</option><option value="TRENDING">Trending</option><option value="CATEGORY">Category</option><option value="SEARCH">Search</option></select><select value={featuredProductDuration} onChange={e=>setFeaturedProductDuration(e.target.value)} className="mt-2 w-full rounded-card border border-graphite-200 px-3 py-2.5 text-sm">{durationOptions.map(d=><option key={d} value={d}>{d} day{d>1?"s":""}</option>)}</select><button disabled={saving!==null} className="mt-3 w-full rounded-card bg-graphite-900 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{saving==="product"?"Featuring…":"Feature product"}</button></form>
 <form onSubmit={createFeaturedStore} className="rounded-card border border-graphite-200 p-4"><h2 className="font-bold text-graphite-900">🏪 Feature a store</h2><p className="mt-1 text-xs text-graphite-600">Put an approved store into the featured store rotation.</p><select required value={featuredStore} onChange={e=>setFeaturedStore(e.target.value)} className="mt-4 w-full rounded-card border border-graphite-200 px-3 py-2.5 text-sm"><option value="">Choose store</option>{vendorStores.map(s=><option key={s.id} value={s.id}>{s.storeName}</option>)}</select><select value={featuredStoreDuration} onChange={e=>setFeaturedStoreDuration(e.target.value)} className="mt-2 w-full rounded-card border border-graphite-200 px-3 py-2.5 text-sm">{durationOptions.map(d=><option key={d} value={d}>{d} day{d>1?"s":""}</option>)}</select><button disabled={saving!==null} className="mt-3 w-full rounded-card bg-graphite-900 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{saving==="store"?"Featuring…":"Feature store"}</button></form></div>
 <h2 className="mb-3 mt-8 text-sm font-bold uppercase tracking-wide text-graphite-600">Live flash deals</h2>{flashDeals.length===0?<p className="text-sm text-graphite-600">No active flash deals.</p>:<div className="flex flex-col gap-2">{flashDeals.map(f=><div key={f.id} className="flex items-center justify-between rounded-card border border-graphite-200 p-3"><div><p className="text-sm font-medium text-graphite-900">{f.name}</p><p className="text-xs text-graphite-600">{f.storeName} · {Number(f.discountPercent)}% off · {formatNaira(Number(f.salePrice))} · ends {new Date(f.endsAt).toLocaleString()}</p></div><button onClick={()=>void cancelFlash(f.id)} disabled={saving===`cancel-${f.id}`} className="rounded-card border border-ember-600 px-3 py-1.5 text-xs font-semibold text-ember-600">{saving===`cancel-${f.id}`?"Removing…":"Remove"}</button></div>)}</div>}
 <h2 className="mb-3 mt-8 text-sm font-bold uppercase tracking-wide text-graphite-600">Featured products</h2>{products===null?<p className="text-sm text-graphite-600">Loading…</p>:products.length===0?<p className="text-sm text-graphite-600">None active right now.</p>:<div className="flex flex-col gap-2">{products.map(f=><div key={f.id} className="flex items-center justify-between rounded-card border border-graphite-200 p-3"><div><p className="text-sm font-medium text-graphite-900">{f.product.name}</p><p className="text-xs text-graphite-600">{f.product.vendor.storeName} · {f.placement} · {f.durationDays}d · {formatNaira(Number(f.price))}</p></div><button onClick={()=>void cancelProduct(f.id)} className="rounded-card border border-ember-600 px-3 py-1.5 text-xs font-semibold text-ember-600">Cancel</button></div>)}</div>}
 <h2 className="mb-3 mt-8 text-sm font-bold uppercase tracking-wide text-graphite-600">Featured stores</h2>{stores===null?<p className="text-sm text-graphite-600">Loading…</p>:stores.length===0?<p className="text-sm text-graphite-600">None active right now.</p>:<div className="flex flex-col gap-2">{stores.map(f=><div key={f.id} className="flex items-center justify-between rounded-card border border-graphite-200 p-3"><div><p className="text-sm font-medium text-graphite-900">{f.vendor.storeName}</p><p className="text-xs text-graphite-600">{f.durationDays}d · {formatNaira(Number(f.price))}</p></div><button onClick={()=>void cancelStore(f.id)} className="rounded-card border border-ember-600 px-3 py-1.5 text-xs font-semibold text-ember-600">Cancel</button></div>)}</div>}
 </div>;
}
