"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, Building2, CalendarDays, CheckCircle2, Clock3, Plus } from "lucide-react";
import { api, ApiError } from "@/lib/api-client";
import { useAuth } from "@/lib/auth-context";

type Partner={id:string;organizationName:string;status:string;eventPlan:string;complimentaryAccess:boolean;complimentaryAccessExpiresAt:string|null};
type Event={id:string;title:string;status:string;startsAt:string;eventPlan:string};

export default function PartnersPage(){
 const {user,loading}=useAuth();
 const [partner,setPartner]=useState<Partner|null>(null); const [events,setEvents]=useState<Event[]>([]);
 const [form,setForm]=useState({organizationName:"",description:"",websiteUrl:"",contactEmail:"",contactPhone:""});
 const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 async function load(){try{const r=await api.get<{partner:Partner|null}>("/api/partner-events/partners/me");setPartner(r.partner);if(r.partner){const e=await api.get<{events:Event[]}>("/api/partner-events/partners/me/events");setEvents(e.events)}}catch{}}
 useEffect(()=>{if(user)void load()},[user]);
 async function register(ev:React.FormEvent){ev.preventDefault();setBusy(true);setError("");setMessage("");try{const r=await api.post<{partner:Partner}>("/api/partner-events/partners/register",form);setPartner(r.partner);setMessage(r.message)}catch(e){setError(e instanceof ApiError?e.message:"Could not submit partner application.")}finally{setBusy(false)}}
 if(loading)return <div className="shell py-16 text-center text-sm text-graphite-600">Loading...</div>;
 if(!user)return <div className="shell py-16"><div className="mx-auto max-w-xl rounded-card border border-graphite-200 bg-white p-7 text-center dark:border-graphite-700 dark:bg-graphite-900"><Building2 className="mx-auto h-10 w-10 text-ember-600"/><h1 className="mt-3 text-xl font-extrabold text-graphite-900 dark:text-white">Partner with TTFL Store</h1><p className="mt-2 text-sm leading-6 text-graphite-600 dark:text-graphite-300">Sign in to register your company and submit events for TTFL Store vendors and customers.</p><Link href="/login?redirect=/partners" className="mt-5 inline-flex rounded-card bg-ember-600 px-5 py-3 text-sm font-bold text-white">Sign in to continue</Link></div></div>;
 if(!partner)return <div className="shell py-8 sm:py-10"><div className="max-w-2xl"><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-ember-600">TTFL Store Partner Network</p><h1 className="mt-1 text-2xl font-extrabold text-graphite-900 dark:text-white">Share your events with businesses and shoppers</h1><p className="mt-2 text-sm leading-6 text-graphite-600 dark:text-graphite-300">Approved partners can publish trade fairs, exhibitions, training, networking and other opportunities through TTFL Store.</p></div><form onSubmit={register} className="mt-7 max-w-2xl space-y-4 rounded-card border border-graphite-200 bg-white p-5 dark:border-graphite-700 dark:bg-graphite-900"><Field label="Company / organization name"><input required value={form.organizationName} onChange={e=>setForm({...form,organizationName:e.target.value})} className="input"/></Field><Field label="Description"><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="input min-h-24"/></Field><Field label="Website"><input type="url" value={form.websiteUrl} onChange={e=>setForm({...form,websiteUrl:e.target.value})} className="input" placeholder="https://"/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Contact email"><input type="email" value={form.contactEmail} onChange={e=>setForm({...form,contactEmail:e.target.value})} className="input"/></Field><Field label="Phone"><input value={form.contactPhone} onChange={e=>setForm({...form,contactPhone:e.target.value})} className="input"/></Field></div>{error&&<p className="rounded-card bg-ember-100 px-3 py-2 text-sm text-ember-700">{error}</p>}{message&&<p className="rounded-card bg-verified-100 px-3 py-2 text-sm text-verified-700">{message}</p>}<button disabled={busy} className="rounded-card bg-graphite-900 px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{busy?"Submitting...":"Apply to become a partner"}</button></form></div>;
 return <div className="shell py-8 sm:py-10"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-ember-600">Partner Portal</p><h1 className="mt-1 text-2xl font-extrabold text-graphite-900 dark:text-white">{partner.organizationName}</h1><div className="mt-2 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-cloud-100 px-2.5 py-1 font-bold dark:bg-graphite-800">{partner.status}</span><span className="rounded-full bg-verified-100 px-2.5 py-1 font-bold text-verified-700">{partner.complimentaryAccess?"Complimentary ":""}{partner.eventPlan} Event Plan</span></div></div>{partner.status==="APPROVED"&&<Link href="/partners/dashboard" className="inline-flex items-center gap-2 rounded-card bg-ember-600 px-4 py-2.5 text-sm font-bold text-white">Manage events <ArrowRight className="h-4 w-4"/></Link>}</div><div className="mt-7 grid gap-4 sm:grid-cols-3"><Stat icon={<CheckCircle2/>} label="Partner status" value={partner.status}/><Stat icon={<CalendarDays/>} label="Event plan" value={partner.eventPlan}/><Stat icon={<Clock3/>} label="Events submitted" value={String(events.length)}/></div></div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-sm font-semibold text-graphite-800 dark:text-graphite-100">{label}</span>{children}</label>}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-card border border-graphite-200 bg-white p-4 dark:border-graphite-700 dark:bg-graphite-900"><div className="flex items-center gap-2 text-graphite-400">{icon}<span className="text-xs font-bold uppercase tracking-wide">{label}</span></div><p className="mt-2 text-lg font-extrabold text-graphite-900 dark:text-white">{value}</p></div>}
