"use client";
import { useEffect, useState } from "react";
import { Loader2, Save, ShieldCheck, Gift } from "lucide-react";
import { api, ApiError } from "@/lib/api-client";

type Program={enabled:boolean;customerReferralsEnabled:boolean;vendorReferralsEnabled:boolean;vendorRewardEnabled:boolean;vendorRewardTier:string;vendorRewardMonths:number;vendorQualification:string};
export default function AdminAffiliatesPage(){
 const[program,setProgram]=useState<Program|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[message,setMessage]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);
 async function load(){try{const r=await api.get<{settings:Record<string,string>}>("/api/affiliates/admin/settings");const s=r.settings;setProgram({enabled:s.affiliate_program_enabled==="true",customerReferralsEnabled:s.affiliate_customer_referrals_enabled==="true",vendorReferralsEnabled:s.affiliate_vendor_referrals_enabled==="true",vendorRewardEnabled:s.affiliate_vendor_reward_enabled==="true",vendorRewardTier:s.affiliate_vendor_reward_tier||"PRO",vendorRewardMonths:Number(s.affiliate_vendor_reward_months||1),vendorQualification:s.affiliate_vendor_qualification||"APPROVED_VENDOR"});}catch(e){setError(e instanceof ApiError?e.message:"Unable to load affiliate settings.");}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function save(){if(!program)return;setSaving(true);setMessage(null);setError(null);try{await api.put("/api/affiliates/admin/settings",program);setMessage("Affiliate settings saved.");}catch(e){setError(e instanceof ApiError?e.message:"Unable to save affiliate settings.");}finally{setSaving(false);}}
 if(loading)return <div className="shell flex min-h-[60vh] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-ember-600"/></div>;
 if(!program)return <div className="shell py-12"><p className="text-sm text-ember-700">{error}</p></div>;
 return <div className="shell py-8 sm:py-10"><div><p className="text-xs font-bold uppercase tracking-wide text-ember-600">Affiliate controls</p><h1 className="mt-1 text-2xl font-bold text-graphite-900">Affiliate program</h1><p className="mt-1 text-sm text-graphite-600">Control referral types, vendor rewards and qualification rules without changing code.</p></div>
 <div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="rounded-card border border-graphite-200 bg-white p-5"><div className="flex items-center gap-3"><ShieldCheck className="h-5 w-5 text-ember-600"/><div><h2 className="font-bold">Program permissions</h2><p className="text-xs text-graphite-500">Choose what affiliates can use.</p></div></div><div className="mt-5 space-y-4"><Toggle label="Affiliate program enabled" value={program.enabled} onChange={v=>setProgram({...program,enabled:v})}/><Toggle label="Customer referral links" value={program.customerReferralsEnabled} onChange={v=>setProgram({...program,customerReferralsEnabled:v})}/><Toggle label="Vendor referral links" value={program.vendorReferralsEnabled} onChange={v=>setProgram({...program,vendorReferralsEnabled:v})}/></div></section>
 <section className="rounded-card border border-graphite-200 bg-white p-5"><div className="flex items-center gap-3"><Gift className="h-5 w-5 text-ember-600"/><div><h2 className="font-bold">Vendor referral reward</h2><p className="text-xs text-graphite-500">The perk shown in the vendor invitation popup.</p></div></div><div className="mt-5 space-y-4"><Toggle label="Vendor reward enabled" value={program.vendorRewardEnabled} onChange={v=>setProgram({...program,vendorRewardEnabled:v})}/><label className="block text-sm font-semibold">Reward plan<select value={program.vendorRewardTier} onChange={e=>setProgram({...program,vendorRewardTier:e.target.value})} className="mt-1.5 w-full rounded-xl border border-graphite-200 px-3 py-2.5 text-sm font-normal"><option value="PRO">Pro Vendor</option><option value="BUSINESS">Business Vendor</option><option value="ENTERPRISE">Enterprise Vendor</option></select></label><label className="block text-sm font-semibold">Reward duration (months)<input type="number" min={1} max={12} value={program.vendorRewardMonths} onChange={e=>setProgram({...program,vendorRewardMonths:Number(e.target.value)})} className="mt-1.5 w-full rounded-xl border border-graphite-200 px-3 py-2.5 text-sm font-normal"/></label><label className="block text-sm font-semibold">Qualification<select value={program.vendorQualification} onChange={e=>setProgram({...program,vendorQualification:e.target.value})} className="mt-1.5 w-full rounded-xl border border-graphite-200 px-3 py-2.5 text-sm font-normal"><option value="APPROVED_VENDOR">Approved vendor</option><option value="FIRST_PAID_VENDOR_PLAN">First paid vendor plan</option></select></label></div></section></div>
 <div className="mt-5 flex items-center gap-3">{message&&<span className="text-sm font-semibold text-verified-700">{message}</span>}{error&&<span className="text-sm text-ember-700">{error}</span>}<button onClick={save} disabled={saving} className="ml-auto inline-flex items-center gap-2 rounded-xl bg-ember-600 px-5 py-3 text-sm font-bold text-white disabled:opacity-60"><Save className="h-4 w-4"/>{saving?"Saving…":"Save affiliate controls"}</button></div></div>;
}
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <button type="button" onClick={()=>onChange(!value)} className="flex w-full items-center justify-between rounded-xl border border-graphite-200 px-4 py-3 text-left"><span className="text-sm font-semibold">{label}</span><span className={`relative h-6 w-11 rounded-full transition ${value?"bg-ember-600":"bg-graphite-200"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow transition ${value?"left-6":"left-1"}`}/></span></button>}
